spring.application.name=pedidos360-bff
server.port=${PORT:8080}

# Microsoft Entra ID. Reemplazar por variables de entorno al ejecutar.
azure.tenant-id=${AZURE_TENANT_ID:REEMPLAZAR_TENANT_ID}
azure.api-client-id=${AZURE_API_CLIENT_ID:REEMPLAZAR_BACKEND_CLIENT_ID}

# CORS del frontend Angular.
app.frontend-origin=${FRONTEND_ORIGIN:http://localhost:4200}

# Base de datos local simple para la demo.
spring.datasource.url=jdbc:h2:mem:pedidos360;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
