name: Build and deploy Angular app to Azure Web App - pedidos360-frontend-diego

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'
          cache-dependency-path: frontend/pedidos360-frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend/pedidos360-frontend
        run: npm ci

      - name: Build Angular
        working-directory: frontend/pedidos360-frontend
        run: npm run build

      - name: Upload Angular artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: frontend/pedidos360-frontend/dist/pedidos360-frontend/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Angular artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app
          path: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A1442195498347BAB478B3D1D221F454 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5AEFE663CA1B43689D5A97404E14F08C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E40643366D69409B8059082164C06026 }}

      - name: Deploy Angular to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pedidos360-frontend-diego'
          slot-name: 'Production'
          package: app
